### PR TITLE
Backend all for product cart, and payment

### PR DESCRIPTION
**Pull request by SoYeonA**

### CODE REVIEW

**Review by allyshia18 — CHANGES_REQUESTED** [review]
Great work! I did have a few callouts/questions 

Cart Controller: do we need clearCart method? Only users have access to the store, correct?

paymentController: getAllPayments was created for us to test only, not to use for the app (do we want to include?)

productController: shouldn't get all products render the product page?

Cart Model: do we need a userId attribute if it's going to be used in 

payment Model: price attribute is that referring to the price of product? It's also labeled as number data type then as string in Payment Factory function

we may need to revisit all AssociateUser functions

Product Model: ProductFactory function we will need to change productPrice datat type to integer

**Review by HolyDois — COMMENTED** [review]
Looks great! I am now answer/piggy backing off of Allyshia's questions/comments

Cart Controller: do we need clearCart method? Only users have access to the store, correct? Yes, that's a great idea

paymentController: getAllPayments was created for us to test only, not to use for the app (do we want to include?) No, we don't want to include.

productController: shouldn't get all products render the product page? Yes, to getallproducts in the cart.

Cart Model: do we need a userId attribute if it's going to be used in? Yes, because only users use the cart (all tables need userId).

payment Model: price attribute is that referring to the price of product? It's also labeled as number data type then as string in Payment Factory function. -I believe it's referring to the subscription.  Jude told her to change it to a number, but I'm not sure why. 

we may need to revisit all AssociateUser functions - I agree

Product Model: ProductFactory function we will need to change productPrice data type to integer - I agree

**Comment by SoYeonA** [comment]
Cart Controller: do we need clearCart method? Only users have access to the store, correct? Yes, that's a great idea
=> Jude asked me to add clearCart, so that when a user checked out, everything in the cart are cleared, no product in his/her cart.

paymentController: getAllPayments was created for us to test only, not to use for the app (do we want to include?) No, we don't want to include.
=>  No, we don’t, so it is commanded out, just in case we need it in the future for stripe etc..

productController: shouldn't get all products render the product page? Yes, to getallproducts in the cart.
=> I commanded out ‘addProductPage’ function that you created before.
Now then all products are rendered to product page by 
router.get('/', getAllProducts); in productRoute.ts
app.use('/api/products', productRoutes); in app.ts
In the cart, only some products that are selected by a certain user, not all products, are shown in his/her cart.

Cart Model: do we need a userId attribute if it's going to be used in? Yes, because only users use the cart (all tables need userId).
=> Yes, Paris’ answer is correct.

payment Model: price attribute is that referring to the price of product? It's also labeled as number data type then as string in Payment Factory function. -I believe it's referring to the subscription. Jude told her to change it to a number, but I'm not sure why.
=> Oh that was my mistake! I changed string in the factory function to number! Thanks a lot!! 
It could refer both the price of product and subscription, depending on what the paymentType is. That’s what Jude told me.

we may need to revisit all AssociateUser functions - I agree
=> I’ve tried several different version for this part, and this is the only combination that worked without any error, and it’s working quite good on all tests. 
If you want to double-check, could you do this ASAP? If it would take some time for you, because of time sensitivity, we can first merge the code to dev so that the frontend team can download and work with it. I am sure there will be more modifications that are needed once both the frontend and backend part are integrated.

Product Model: ProductFactory function we will need to change productPrice data type to integer - I agree
=> Jude asked it with number and I agree with that because some price could be $19.99, not just $20

**Review by HolyDois — APPROVED** [review]
Now that all the questions are answered I believe we can now merge the backend.

**Review by allyshia18 — APPROVED** [review]

**Pull request merged**
